### ISSUE TITLE
SVG to JSON converter not working for Mac paths

### ISSUE THREAD

**Issue by zicvic** [South-Paw/react-vector-maps#16]
I might not have spent to much time on this yet so please point me in the correct direction if I'm wrong. But I'm trying to use this library to convert my SVG images to JSON files but I get this error: 

```
(node:79418) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'resources\output'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at asyncForEach (/<path_to_repo>/node_modules/@south-paw/react-vector-maps/maps/convert-svgs.js:57:22)
    at asyncForEach (/<path_to_repo>/node_modules/@south-paw/react-vector-maps/maps/convert-svgs.js:7:11)
    at ConvertSVGs.run (/<path_to_repo>/node_modules/@south-paw/react-vector-maps/maps/convert-svgs.js:54:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:79418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:79418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Get the same result when using the absolut path as well get this something like this: 
`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/some_user/path/to/resources\output`. To me it seems like this is using Windows formated paths? Is this something that will be fixed in the 3.0 or what is the plan for this?

**Comment by South-Paw** [comment]
Thanks for raising this. You're probably right that it is to do with Windows paths.

I'm moving the converter to a new documentation site which would solve any platform issues as it'd be in browser - I admittedly wasn't thinking about Mac when I wrote the converter script 😅
