### ISSUE TITLE
Yarn Repository Not Found

### ISSUE THREAD

**Issue by MatheusRV** [South-Paw/react-vector-maps#9]
Arguments: 
  /root/.nvm/versions/node/v10.16.3/bin/node /root/.nvm/versions/node/v10.16.3/bin/yarn add @south-paw/react-vector-map

PATH: 
  /root/.vscode-server/bin/f06011ac164ae4dc8e753a3fe7f9549844d15e35/bin:/root/.nvm/versions/node/v10.16.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/HashiCorp/Vagrant/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/nodejs/:/mnt/c/Users/Teste/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Teste/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/Teste/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/Administrator/Ubuntu:/mnt/c/Users/Teste/AppData/Roaming/npm:/snap/bin

Yarn version: 
  1.17.3

Node version: 
  10.16.3

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/@south-paw%2freact-vector-map: Not found
      at Request.params.callback [as _callback] (/root/.nvm/versions/node/v10.16.3/lib/node_modules/yarn/lib/cli.js:66830:18)
      at Request.self.callback (/root/.nvm/versions/node/v10.16.3/lib/node_modules/yarn/lib/cli.js:140464:22)
      at Request.emit (events.js:198:13)
      at Request.<anonymous> (/root/.nvm/versions/node/v10.16.3/lib/node_modules/yarn/lib/cli.js:141436:10)
      at Request.emit (events.js:198:13)
      at IncomingMessage.<anonymous> (/root/.nvm/versions/node/v10.16.3/lib/node_modules/yarn/lib/cli.js:141358:12)
      at Object.onceWrapper (events.js:286:20)
      at IncomingMessage.emit (events.js:203:15)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by South-Paw** [comment]
Copy pasting a stack trace into an issue is not helpful to an OSS maintainer - you haven't described your issue whatsoever and you'll usually find this would just get it closed with no response.

FYI you have spelt the package name wrong - it's `@south-paw/react-vector-maps` not `@south-paw/react-vector-map`

**Comment by South-Paw** [comment]
I've also made a change to the readme where you might've gotten the wrong package name from.
